# ./docker-compose.yml

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: investpw
      POSTGRES_DB: investdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports: # Adicione esta porta para conseguir se conectar via DBeaver/etc. se precisar
      - "5432:5432"

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app # Mapeia o código local para o container para live-reload
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+asyncpg://invest:investpw@db/investdb"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules # Evita que o node_modules local sobrescreva o do container
    depends_on:
      - backend

volumes:
  db_data: