version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: invest
      POSTGRES_PASSWORD: investpw
      POSTGRES_DB: investdb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://invest:investpw@db:5432/investdb
      SECRET_KEY: junior-secret-key
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  db_data: